services:
  virae-pdf:
    build:
      context: ./engine/pdf
      dockerfile: Dockerfile.fat
    container_name: virae-pdf-engine
    ports:
      - '8080:8080'
    environment:
      - LANGS=pt_BR
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLELOGIN=false
      - UI_APPNAME=Virae PDF
      - UI_APPNAMENAVBAR=Virae PDF
      - UI_HOMEDESCRIPTION=Editor de PDF completo do Virae
      - SYSTEM_DEFAULTLOCALE=pt-BR
      - SYSTEM_ROOTURIPATH=/engine/pdf
      - SYSTEM_ENABLEANALYTICS=false
      - DISABLE_PIXEL=true
    volumes:
      - virae-pdf-data:/configs
    restart: unless-stopped

volumes:
  virae-pdf-data:
