services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest-fat
    container_name: virae-stirling-pdf
    ports:
      - '8080:8080'
    environment:
      - LANGS=pt_BR
      - DOCKER_ENABLE_SECURITY=false
      - SECURITY_ENABLELOGIN=false
      - UI_APPNAME=Virae PDF
      - SYSTEM_DEFAULTLOCALE=pt-BR
      - SYSTEM_ROOTURIPATH=/stirling
    volumes:
      - ./stirling-config/customFiles:/customFiles
      - stirling-data:/configs
    restart: unless-stopped

volumes:
  stirling-data:
